In [38]:
import timeit
import pandas as pd
import csv
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder

transactions = []
with open('../../data/store_data.csv', 'r') as file:
    for row in csv.reader(file):
        transactions.append(row)
te = TransactionEncoder()
te_ary = te.fit_transform(transactions)
transactions_df = pd.DataFrame(te_ary, columns=te.columns_)

print(f'f1 timeit = {timeit.timeit(lambda: apriori(pd.DataFrame(transactions_df), min_support=0.005, use_colnames=True, max_len=1), number=1)}')
# f1 = apriori(pd.DataFrame(transactions_df), min_support=0.005, use_colnames=True, max_len=1)
# a = f1['itemsets'].tolist()

f1 timeit = 0.0016911150014493614


In [1]:
import sys
sys.path.append('/home/daehan/PycharmProjects/associative-classifier-pos-neg-rules/src/util')
import util

util.apriori_of_size_k(pd.DataFrame(transactions_df), min_support=0.005, use_colnames=True, k=1)


AttributeError: module 'util' has no attribute 'apriori_of_size_k'

In [8]:
import csv
import timeit
import numpy as np
import util
import pandas as pd

with open('../../data/training_dataset.csv', 'r') as file:
    training_set = [list(filter(None, row)) for row in csv.reader(file)]
transactions_df = util.convert_trans_to_df(training_set)
itemsets_df = pd.DataFrame(transactions_df.drop(['1', '0'], axis=1)).values


matrix = np.random.randint(0, 900, size=(10000, 3))
matrix = matrix.astype('int16')
matrix

array([[507, 292, 457],
       [ 58, 405, 414],
       [470, 351, 473],
       ...,
       [502, 633, 217],
       [620, 877, 393],
       [225, 378,  30]], dtype=int16)

In [12]:
itemsets_df[:, matrix]

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        ...,
        [False,  True, False],
        [False, False, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False, False],
        [False, False, False],
        ...,
        [False,  True, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        ...,
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       ...,

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        ...,
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        ...,
        [False, False, False],
        [False, False, False],
        [False,

In [16]:
import multiprocessing
import timeit

def treat_chunks(chunk):
    return itemsets_df[:, chunk]

def single():
    return np.all(itemsets_df[:, matrix], axis=2)

def multi():
    split = np.array_split(matrix, 24)
    with multiprocessing.Pool() as pool:
        temp =  pool.map(treat_chunks, split)
    temp = np.concatenate(temp, axis=1)
    _bools = np.all(temp, axis=2)
    return _bools

In [17]:
# timeit.timeit(lambda: multi(), number=1)
multi()

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [18]:
# timeit.timeit(lambda: single(), number=1)
single()

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [8]:
import numpy as np
rule = [
	{'antecedent': frozenset[1], 'consequent': '2'},
	{'antecedent': frozenset[1, 2], 'consequent': '2'}
]
arr = np.array(rule)
arr[arr == 1]

array([], dtype=object)